### ISSUE TITLE
Stop to commit Travis API key in the repository

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/meilix#148]
- Issue type: Feature request 

### Short description

Every person has its own unique secure key included in the .travis.yml file and the idea is to not include the .travis.yml file is its been committed.

**Comment by abishekvashok** [comment]
You need to disable enabling his/her unique key and implement that of fossasia. (Releases should be made only on this repo). If you want to have releases so that you can test things you will have two options:

1. Don't track the changes made in the .travis.yml file.
2. Run the build.sh file on your own machine.

Option 2 may require some time based on your PC's processing power.


**We can't remove .travis.yml or ignore it, you won't get it if you clone and Travis will error. See the PR for additional clarification.**

**Comment by meets2tarun** [comment]
@abishekvashok 
> Don't track the changes made in the .travis.yml file.

How does this option possible?

**Comment by tabesin** [comment]
Locally, on your machine.

**Comment by abishekvashok** [comment]
@meets2tarun when you track files before commit-ing;

```
git add -u
git reset -- .travis.yml
```

**But remember Travis won't get your new keys. It will keep the old ones.**

Another option would be revert a commit after all testing is done:
`git revert <commit>`

**Comment by tabesin** [comment]
ok, so let's close it.
