### ISSUE TITLE
Bringing Linux Customization to the End User

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix#47]
Various flavors of linux exist. Ubuntu has a lot of derivatives for different use cases: education, office, low-memory, … . How can we allow the average users to customize their own linux distribution?

## The User Interface

A simple user interface can be a website as prototyped by codersos/create. The users can choose among different flavors of the UI, programs an packages. Next, they submit their customization to a server and get feedback about the build. When the build is done, they get notified or download the file automatically.

## Architecture

The architecture consists of several components:

- The website for the user
- The logic (proxy) to create a build
- The build services (Travis, self-hosted, gitlab-ci, …)
- The repository with the linux build
- The meta packages to keep older builds updated
- Picture of the Architecture

### (1) Customization

The user goes to the github pages served website. A specification is created. This spec can be downloaded, loaded, sent to the proxy. A proxy is chosen by the website based on availability.

### (2) Build Server is Chosen

The proxy chooses a build sever to send the spec to.

- Travis and Gitlab-CI
- In these cases the proxy passes the specification to the repository by creating a commit with a tag and pushing this.
- Heroku
- This is an own build service.
- A way to recognize whether a build was successful/which state it has, … is communicated back to the website.

### (3) Image Build

The repository is built by the build service. The correspnding image and output is pushed to a release somewhere.

During the build, the meta packages are used. They allow updating the resulting distribution in the future.

## Collaborating

Questions are discussed in issues.

In order to spread the knowledge, students can not merge their own pull-requests but those others. (Inspiration)

The APIs are defined and discussed first:

- We keep the architecture clean
- development details do not creep through several repostories and increase required expert knowledge for contribution
- The development speed is constant
- We document and talk which is a basis for collaboration

###  Possible Customization

- Hotel - See meilix
- Events
   - connect to wifi
   - turn notifications off
   - browser start page is event
   - presentation tools like libre office are installed
   - owncloud/nextcloud to share files and slides, authenticated
   - onedrive, dropbox?
   - same user/password
- Programming clubs?
- environments and languages
  - see CoderDojoOs
Home & Office
- not sure if this is important as there is so much

## Related Work

Tools like customizer exist as a GUI and can be automated using continuous integration servers such as Travis. The pager about the live-addon-maker provides further research.

Original: http://niccokunzmann.github.io/blog/2017-04-19/customized-linux-distribution-by-click

**Comment by xeon-zolt** [comment]
@mariobehling  i was thinking why are we trying to build it on a server it costs a server plus time to build it then to host the built image
instead of that why don't we try improving the installation process like where the user can choose his flavour then apps like 
* owncloud/nextcloud to share files and slides, authenticated
* onedrive, dropbox?
* libre office

maybe configuration too like turn notifications off

like this
![gycckdu](https://cloud.githubusercontent.com/assets/4529442/25385498/e00bc10e-29e1-11e7-8d79-594c84c65f2c.png)

and

![installing_antergos_linux_7](https://cloud.githubusercontent.com/assets/4529442/25385060/56b5920a-29e0-11e7-8b55-04b6f81ffa20.png)

**Comment by niccokunzmann** [comment]
@xeon-zolt Cool idea. Where did you get then imaged from?

**Comment by xeon-zolt** [comment]
they are of antergos linux ! i was in touch with the developer when discussing about drivermanager GUI for antergos linux

**Comment by mariobehling** [comment]
Downloading an image with tons of options could be huge. Better provide a web ui. Server cost is not really a concern these days. The goal of this project is not a general purpose distro. There are enough already.  We have specific use cases eg. Events. We want to solve what we need here.

**Comment by meets2tarun** [comment]
Since the problem is related to the customization of Linux distribution by an average user. This means that one doesn't have to code all the things up for the building/customization of the OS.

Talking only about the minimal customization of the OS, there are so many web UI out there which help us to do so, but none of them is so that they will make the distro full-proof according to our desire 100%. Some of them are SUSEStudio, UKT etc. They all have the different base. We also don't have all types of desktop flavors present in the web UI. 

Taking a look at some of the online distro building web app:

1. [**Instalinux**](http://www.instalinux.com) - Here one can choose the base of the distribution and best part is that there are many. This will create an approx 30mb ISO image which can be booted to fetch the other packages from the Internet.

2. [**SUSE Studio**](https://susestudio.com/) - It is based on SUSE and it will make a final ISO. In terms of personalization, it is much better that Instalinux but its has a single base.

3. [**Live Magic**](https://chris-lamb.co.uk/projects/live-magic) - It has a base of Debian/Ubuntu. It provides an interface which will follow to build the distro. 

4. [**Linux Live Kit**](http://www.linux-live.org/) - It's a set of shell scripts to create a distro from an already installed Linux distro.

5. [**Remastersys**](http://www.remastersys.org/) - It will clone your running Debian/Ubuntu and make a live CD. This makes customization really easy because you are actually running it and can easily make changes in it.

6. [**Ubuntu Customization Kit**](https://apps.ubuntu.com/cat/applications/precise/uck/) - It's a package for Ubuntu to create having a limited number of customization option. 

If I have to choose one of the above mention options, I will go for the first one since of its lots of base option and in this, we can choose packages from its derivatives also like making a distro base of Ubuntu and deriving packages from Edubuntu.

It will also be a problem to customize the pre-made distro in the future if we want and to release an ISO rather than again building it from starting.

To achieve the target of making event distro as specification mention in [**issue**](https://github.com/fossasia/labs.fossasia.org/issues/135), none of the above can help to accomplish the OS with 100% desire, one has to refrain from some of the features that may be important.

I have an idea of customizing [**CodersOS**](https://github.com/CodersOS/create) to put our desire option for the building of the distro. This will help us to get the distro as well will also be easy for the average users to customize the distro according to its desire.

**Comment by xeon-zolt** [comment]
@meets2tarun what idea ?

**Comment by meets2tarun** [comment]
@xeon-zolt It has been already mentioned in the last 3 lines?

**Comment by Abhi2424shek** [comment]
Ok,  this seems interesting, just like our build script we can get users to choose their flavours, logically it would be easy, we would need to provide a website with an active GUI, which generates the required distribution. IMO, we should start one by one interactively so that users with little knowledge could easily get through. Using a CI for building the image doesn't seem to be a nice idea when this repository itself is used, however, we could make Travis run and build using another repository and send the .Iso file to the user's email address or put it into a cloud and put it there for maybe 24 hours or so. Using heroku would be much more simple and would be using another logic.

So, we would need the following repositories:
1.) Repository for the web app which generates a build script
2.) Travis CI or other CI build repository which gets the build script and runs it, then sends to the user or notifies him by sorting it either forever or for a certain amount of time.

There's also a slight possibility that someone else would generate a same distribution as done by some other person, so it would be better if we could store then somewhere. This is the pros and cons of such a storage:
*Pros:*
- User doesn't have to wait if the distro is already generates by someone else
- The User experience would be good as user doesn't have to wait.

*cons:*
- large amount of storage would be needed.

What are all your thoughts?

**Comment by xeon-zolt** [comment]
@Abhi2424shek its a bad idea to store already generated distro as the number of combinations can be huge

**Comment by Abhi2424shek** [comment]
Yea, I know that, it would be huge, but if we could provide it somehow it would enhance the user experience but I really don't want to do it, it's just a suggestion.

**Comment by xeon-zolt** [comment]
I was thinking that to solve this we can have a login so and their people can manage their build and link it with their cloud storage like Dropbox or gdrive and we can save the configuration the user chose and upload the build to his cloud storage and if he want to apply changes in future he can manage that easily

**Comment by Abhi2424shek** [comment]
Maybe we could let users do that, in addition if he really wants make the link live to others as well for the configuration he generated. Is it feasable? We would need to verify the sha sum integrity maybe every day or so.

**Comment by meets2tarun** [comment]
I think the best way is to customize the [CodersOS](https://github.com/CodersOS/create) to get the desired OS. We can add more configuration and personalization option as per our requirement. We can have all the made configuration to get saved automatically so if one needs the same OS, he/she don't have to build it again.

**Comment by Abhi2424shek** [comment]
Can someone create the required repositories? It would be better to follow up here as we have a everyone up. Thoughts?

**Comment by mariobehling** [comment]
There are different ideas in this discussion. I see things that could work, but some approaches are somehow complex and have a number of dependencies. Let's keep it rather simple for the beginning. If someone wants to start a more sophisticated approach, please start it in your repo and after some initial work we can later move it to the organization, if it is suitable.

So, before we ask contributors to build a complete build system with all kinds of options and choices for desktop environments, let's start small.

As a first step, we need:
* scripts to create distros the different use cases (hotel/meilix, events, lubuntu with lxqt)
* meta packages, for each distro that offers customized startpage etc.
* documentation how to create each option

**Comment by Abhi2424shek** [comment]
We could base the scripts and metapackages on those which are used in meilix. For scripts we need to go with a flow, Ubuntu maybe?

**Comment by meets2tarun** [comment]
It would be different in case of difference in the base of the distro. I
prefer a system which let us choose between different base like Ubuntu,
Debian, Fedora, Arch, etc as per our requirement.

**Comment by mariobehling** [comment]
> I prefer a system which let us choose between different base like Ubuntu, Debian, Fedora, Arch, etc as per our requirement.

For the beginning please use Debian and Ubuntu. 

@meets2tarun Please avoid answers from email keeping the email conversation in the answer. Thanks.

**Comment by xeon-zolt** [comment]
made a script to choose DE for building the ISO with base ARCH LINUX similar we can do with melix script 
i will add arguments to this script later to be used as one line command

script --> https://github.com/xeon-zolt/Event-linux/blob/custom-build/buildAVA
repo to use script with --> https://github.com/xeon-zolt/Event-linux/tree/custom-build

**Comment by mariobehling** [comment]
@xeon-zolt Nice. 

Though not so relevant for this project. Linux projects often have some differences in the detail and I don't see how we could support many different Linux distros and desktop environments. Focus for now is Debian and Ubuntu and LXQT. LXQT is not covered by many distros. Cheers. I am closing this discussion now. Great input everyone!

**Comment by meets2tarun** [comment]
I want if the issue has been closed, something should get started.
As @mariobehling Sir said to start with the small one.
I am thinking to club everyone ideas related to this project which is beneficial to us.
Thinking of to start with a webapp design for the one to have options of customization proceed by personalization. Selection of distro base between Ubuntu, Debian, meilix. If ubuntu base is there we can club the required metapackages from lubuntu, edubuntu. From input by @Abhi2424shek, we can have different scripts of bases and their metapckages.

**Comment by mariobehling** [comment]
>  If ubuntu base is there we can club the required metapackages from lubuntu, edubuntu

Not sure, what you mean. Creating the meta-packages is part of this project. We will not be using the meta-packages that exist in Ubuntu.

**Comment by mariobehling** [comment]
Please investigate and learn more about meta-packages https://github.com/fossasia/meilix/issues/48
