### ISSUE TITLE
Investigate Meta-Packages in Meilix and propose ways for configuration

### ISSUE THREAD

**Issue by mariobehling** [fossasia/meilix#48]
There are metapackages in meilix. These meta-packages can help to define details of a distro including which packages are included, start page and search engines of browsers etc.

Please check out the existing meta-packages and update them. Find out what needs to be changed in order to change browser search engines etc. and update your findings in the Readme.md

Next steps would be to make a list of items that we will include in the meta-package.

**Comment by Abhi2424shek** [comment]
Here's a list of all metapackages used in meilix along with their contents or uses.

| Metapackages Name | Contents or uses | inclusion |
| ubuntu-standard | standard utilities for Ubuntu system | X |
| casper | A hook for intrafms-tools to boot live systems | X |
| lupin-casper | Adds support for loop mount installations over casper | X |
| laptop-detect | used to detect laptops | X |
| os-prober | used to detect the operating systems in the harddisk | X |
| grub | bootloader | X |
| linux-generic | set of linux utilities for linux systems | X |
| lxsession | session starter for LXDE |
| lightdm | desktop manager for LXDE |
| lightdm-gtk-greeter | gtk greeter for LXDE |
| gvfs-backends | gvfs file system |
| seahorse | gnome encryption manager |
| network-manager-gnome | gnome network manager |
| xorg | X server | X |
| dbus-x11 | x11 daemon | X |
| openbox | window manager |
| ubiquity-frontend-gtk | gtk front-end for ubiquity live installer |
| vlc | vlc media player |
| xfce4-mixer | Xfce mixer |
| gstreamer0.10-alsa | gstreamer plugin for alsa |
| pulseaudio | audio manager |
| pavucontrol | audio controller |
| mozilla-firefox | web browser |
| lxpanel | | LXDE panel |
| mozilla-plugin-vlc | vlc media player plugin for Firefox |
| lubuntu-core | lubuntu core packages |
| jokey-gtk | 
| lubuntu-restricted-extras | etra packages like video decoders |
| chromium | chromium browser |
| lxrandr | moniter settings manager |
| flash-plugin-installer | flash plugin installer |
| google-talkplugin | plugin for Google talk |
| pidgin | im client |
| gcalculator | gnome calculator |
| gpicview | gnome picture viewer |
| evince | document viewer |
| libqtwebkit4 | qt web kit |
| skype | im client |
| pingus | game |
| nikwi | game |
| gnome-games | games |
| supertux | game |
| tuxpaint | tux paint |
| gimp | gimp |
| inkscape | inkscape |
| Libre office packages (it includes many metapackages which I haven't mentioned as it's like a stack) | libre office |
| East asian fonts and language packs  (it includes many metapackages which I haven't mentioned as it's like a stack) | fonts and language packs | X |
| ibus packages  (it includes many metapackages which I haven't mentioned as it's like a stack) | ibus | X |
| Plymouth packages |  (it includes many metapackages which I haven't mentioned as it's like a stack) | Plymouth | X |
| Python | Python |
| debhelper | helper program | X |
| gksu | graphics froentends for sudo | X |
| intltool | internationalization of XML | X |

Can we have a discussion on which all packages we should have, we could edit this list. I have added `X` for packages that are essential, after discussions of rest we could add new packages to this list and add X to include them. Thoughts?

CC: @meet2tarun, @xeonjolt, @niccokunzmann, @mariobehling.

**Comment by meets2tarun** [comment]
@Abhi2424shek These are the meta-packages for the meilix. We can apply your idea to replace the unrequired meta package with the required one respectively for event and hotel-os.
But in my opinion, it is not favorable to alter with meilix source rather than we can use it to derive the event and hotel-os with the above idea and the idea presented by @niccokunzmann Sir in the fossasia/meilix channel of gitter (some picture illustration). What do you think fo this?
cc: @mariobehling @xeon-zolt

**Comment by Abhi2424shek** [comment]
@meets2tarun I saw that, but instead of creating 2 scripts we could use a single script for it.

**Comment by meets2tarun** [comment]
@Abhi2424shek  A single script both for event and hotel. Did you mean that? Please clarify.

**Comment by Abhi2424shek** [comment]
Yea @meets2tarun, I meant a single script, you could pass an extra parameter to the build script and tell it which is to build, currently we could define the architecture, 32 bit od 62 bit etc by passing an argument(see the first few lines). Likewise we could pass a parameter, then depending on it we could have if conditions in the script. I think since we keep the base same for both the OSs what matters is the front-end, we could simply add if conditions for them, 99%ly modifying the metapackages work. If we follow this approach, we need to:
- define which all metapackages should be there for hotel os and events os.
- add proxy support
- add webapp

Optionally: we could let the user choose additional metapackages and programs like window manager or desktop environments.

Thoughts?

**Comment by meets2tarun** [comment]
@Abhi2424shek What are the conditions which are going to be in the if/else statement which defines the architecture?
And nothing other than altering with these lines, the whole script of build.sh will be same irrespective of the OS. Right?

**Comment by Abhi2424shek** [comment]
Yes. As we are applying settings we might have two different sets of settings for default settings for different distro, and metapackages in the if else if, blocks. :)

**Comment by abishekvashok** [comment]
@mariobehling what else we need here now?
