### ISSUE TITLE
Adding Lxqt to the generator branch of meilix

### ISSUE THREAD

**Issue by xeon-zolt** [fossasia/meilix#64]
- Issue type: Feature 

### Short description

lxqt is a desktop environment and we need to use it for next part 

### Usecase

it is a lightweight DE so it can run on low spec PC too plus after adding this we should be working on configuring it for presentations

**Comment by meets2tarun** [comment]
Successfully tested the changes of implementation of LXQT in local and on Travis by altering the build.sh
[here](https://travis-ci.org/meets2tarun/meilix/builds/245057058?utm_source=github_status&utm_medium=notification)
It's not deployed due to tag issue but the matter of the fact is that it build successfully.
Now I'll check other files responsible for the desktop then will make a PR.

**Comment by niccokunzmann** [comment]
fossasia/meilix-generator#22 - related

    fossasia/meilix-generator#22

**Comment by xeon-zolt** [comment]
@meets2tarun attempted booting it ? did it boot with lxqt as DE?

**Comment by meets2tarun** [comment]
#84 LXQt can be found in master now.
Does the changes can be seen in generator branch too?
@xeon-zolt

**Comment by xeon-zolt** [comment]
we are using mkiso for generator branch now so @meets2tarun we need to update  the link of LXQT ISO generated by master and we should also clean the generator branch as it only use single script

**Comment by tabesin** [comment]
Could the ticket be closed?
